# Analisis Exloratorio de Datos (EDA)

## Imports y Carga de Datos

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Carga de datos
df = pd.read_csv('/workspace/data/raw/screen_time_mental_health.csv')

In [4]:
df.head()

,subject_id,sex,screen_time_index,est_leisure_screen_hours,sleep_quality_index,avg_sleep_hours,midsleep_weekend_hours,social_jetlag_hours,bdi_total,depressed
0,1,Boy,3.333,4.64,2.25,8.36,4.58,1.92,6,0
1,2,Girl,3.333,4.07,2.50,7.31,5.42,2.25,7,0
2,3,Boy,3.333,4.07,2.00,8.75,5.50,2.62,27,1
3,4,Boy,4.333,6.07,1.50,8.17,6.62,3.96,22,1
4,5,Boy,1.667,0.50,2.50,8.88,4.12,1.79,3,0

In [6]:
dataframe.head()

,subject_id,screen_normal_day_1to6,screen_weekday_1to6,screen_weekend_1to6,sqi_fall_asleep_1to6,sqi_repeated_awake_1to6,sqi_disturbed_1to6,sqi_early_awake_1to6,bdi_item_01,bdi_item_02,...,bdi_item_12,bdi_item_13,bdi_item_14,bdi_item_15,bdi_item_16,bdi_item_17,bdi_item_18,bdi_item_19,bdi_item_20,bdi_item_21
0,1,2,3,5,1,3,2,3,0,1,...,0,1,0,0,0,0,0,1,0,0
1,2,3,3,4,4,2,3,1,1,0,...,1,1,0,1,1,0,0,0,1,0
2,3,3,3,4,3,1,3,1,1,1,...,2,1,1,1,1,1,1,2,2,1
3,4,4,4,5,2,1,2,1,0,1,...,3,0,0,2,2,1,0,0,1,0
4,5,3,1,1,2,2,4,2,0,0,...,0,0,0,0,1,0,1,0,0,0